from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


ExecutionOutcome = Literal[
    "success",
    "failed",
    "manual_review",
    "duplicate",
]


class ExecutionLogCreate(BaseModel):
    """Completed workflow execution event reported by n8n."""

    model_config = ConfigDict(extra="forbid")

    lead_id: str | None = None
    workflow_name: str = Field(min_length=1, max_length=200)
    outcome: ExecutionOutcome
    error_type: str | None = Field(default=None, max_length=200)
    error_message: str | None = Field(default=None, max_length=2000)
    metadata: dict[str, Any] = Field(default_factory=dict)
    passthrough: dict[str, Any] | None = None


class ExecutionLogRead(BaseModel):
    id: str
    lead_id: str | None
    workflow_name: str
    started_at: str
    finished_at: str | None
    outcome: str
    error_type: str | None
    error_message: str | None
    metadata: dict[str, Any]


class ExecutionLogEnvelope(BaseModel):
    log: ExecutionLogRead
    passthrough: dict[str, Any] | None = None


class StaffNotificationCreate(BaseModel):
    """Internal staff alert generated by the n8n workflow."""

    model_config = ConfigDict(extra="forbid")

    lead_id: str
    customer_name: str = Field(min_length=1, max_length=200)
    urgency: str | None = Field(default=None, max_length=50)
    classification: str | None = Field(default=None, max_length=100)
    message: str = Field(min_length=1, max_length=2000)


class StaffNotificationRead(BaseModel):
    notification_id: str
    lead_id: str
    customer_name: str
    urgency: str | None
    classification: str | None
    message: str
    created_at: str
